apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-secrets
  namespace: hfg-dev
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-secrets_certbot-sa
  namespace: hfg-dev
subjects:
- kind: ServiceAccount
  name: certbot-sa
roleRef:
  kind: Role
  name: update-secrets
  apiGroup: rbac.authorization.k8s.io
