apiVersion: v1
kind: Service
metadata:
  name: hfg-server
  labels:
    app: hfg
    tier: server
spec:
  ports:
  - name: http-port
    port: 8090
    targetPort: 8090
  - name: https-port
    port: 8091
    targetPort: 8091
  selector:
    app: hfg
    tier: server
