apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hfg-server
  labels:
    app: hfg
    tier: server
spec:
  selector:
    matchLabels:
      app: hfg
      tier: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hfg
        tier: server
    spec:
      containers:
      - image: byronstar/hfg-programming:latest
        name: server
        env:
        - name: HFG_DATA
          value: hfg-data
        ports:
        - containerPort: 8091
        - containerPort: 11203
        - containerPort: 11204
      imagePullSecrets:
        - name: dockerhub
      #   volumeMounts:
      #   - mountPath: /var/lib/hfg-data
      #     name: hfg-data
      # volumes:
      # - name: hfg-data
      #   persistentVolumeClaim:
      #     claimName: hfg-data-claim
      # kubectl create secret generic dockerhub --from-file=.dockerconfigjson=~/.docker/config.json --type=kubernetes.io/dockerconfigjson
