apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Add upstream for letsencrypt job
    upstream certbot {
      server certbot:8080 max_fails=0 fail_timeout=1s;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name  hfg.hopto.org;
      location / {
        add_header Content-Type text/plain; # Prevents download
        return 200 "Hello world! Kubernetes + Let's encrypt demo.";
      }
      # Redirect all traffic in /.well-known/ to letsencrypt
      location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://certbot;
      }
    }
