apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: hfg
    tier: nginx
spec:
  externalIPs: ["184.172.252.200"]
  selector:
    app: hfg
    tier: nginx
  ports:
  - name: certbot
    protocol: "TCP"
    port: 80
  - name: http-port
    port: 8090
    targetPort: 8090
  - name: https-port
    port: 8091
    targetPort: 8091
